apiVersion: v1
kind: Service
metadata:
  name: subscription  # name of the service
spec:
  type: LoadBalancer
  selector:
    app: subscription
  ports:
  - port: 80   # port of the service
    targetPort: 9696   # port of the pod
